language: node_js
node_js:
  - "10"

jobs:
  include:
  - name: Client Pipeline
    if: commit_message ~= /\bFE\b/ 
    env: ROOT_FOLDER=client
  - name: Server Pipeline
    if: commit_message ~= /\bBE\b/ 
    env: ROOT_FOLDER=server

script:
  - cd $ROOT_FOLDER
  - npm install
  - npm test

notifications:
  email: false
