version: '3'

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - /WORK/csv-challenge/server/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.backend=server"
      - "traefik.frontend.rule=PathPrefixStrip:/api/"
      - "traefik.port=8080"

  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    command: npm start
    volumes:
      - /WORK/csv-challenge/client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=client"
      - "traefik.port=3000"